name: fb
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  google_fonts: ^0.3.2
  flutter_bloc: ^3.1.0
  flutter_icons: ^1.0.0+1
  percent_indicator: ^2.1.1+1
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/pic.jpeg
  
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-BlackItalic.ttf
        - asset: fonts/Montserrat-Black.ttf
        - asset: fonts/Montserrat-BoldItalic.ttf
        - asset: fonts/Montserrat-Bold.ttf
        - asset: fonts/Montserrat-ExtraBoldItalic.ttf
        - asset: fonts/Montserrat-ExtraBold.ttf
        - asset: fonts/Montserrat-ExtraLightItalic.ttf
        - asset: fonts/Montserrat-ExtraLight.ttf
        - asset: fonts/Montserrat-Italic.ttf
        - asset: fonts/Montserrat-LightItalic.ttf
        - asset: fonts/Montserrat-Light.ttf
        - asset: fonts/Montserrat-MediumItalic.ttf
        - asset: fonts/Montserrat-Medium.ttf
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-SemiBoldItalic.ttf
        - asset: fonts/Montserrat-SemiBold.ttf
        - asset: fonts/Montserrat-ThinItalic.ttf
        - asset: fonts/Montserrat-Thin.ttf
    - family: Lato
      fonts:
        - asset: fonts/Lato-BlackItalic.ttf
        - asset: fonts/Lato-Black.ttf
        - asset: fonts/Lato-BoldItalic.ttf
        - asset: fonts/Lato-Bold.ttf
        - asset: fonts/Lato-Italic.ttf
        - asset: fonts/Lato-LightItalic.ttf
        - asset: fonts/Lato-Light.ttf
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-ThinItalic.ttf
        - asset: fonts/Lato-Thin.ttf
